### ISSUE TITLE
Audio Sampler - Linux - Errors when scanning/running the plugin

### ISSUE THREAD

**Issue by crshrprt** [arunas-cesonis/live-sampler#16]
Thank you for this interesting plugin.

I'm trying to run it on Linux, Debian sid, however it doesn't work in any of the hosts/DAWs I tried, both the vst3 version from the Release and a self compiled one.

I got the following errors:

Carla (when trying to run it)
```
JUCE Assertion failure in juce_VST3PluginFormat.cpp:999
JUCE Assertion failure in juce_VST3PluginFormat.cpp:3802
[carla] Plugin failed to load, error was:
Failed to get plugin description
```

Ardour (in the plugin manager window, plugin is marked with an ERROR STATUS)
```
VST3 module-path '/home/user/Audio/Plugins/.vst3/Audio Sampler.vst3/Contents/x86_64-linux/Audio Sampler.so'
[Info]: Scanning: /home/user/Audio/Plugins/.vst3/Audio Sampler.vst3
[ERROR]: Could not load VST3 plugin '/home/user/Audio/Plugins/.vst3/Audio Sampler.vst3/Contents/x86_64-linux/Audio Sampler.so': /home/user/Audio/Plugins/.vst3/Audio Sampler.vst3/Contents/x86_64-linux/Audio Sampler.so: cannot allocate memory in static TLS block
Cannot load VST3 module: '/home/user/Audio/Plugins/.vst3/Audio Sampler.vst3/Contents/x86_64-linux/Audio Sampler.so'
Scan Failed.
```

BespokeSynth (when scanning for new plugins)
```
Scan complete
The following files appeared to be plugin files, but failed to load
correctly:
Audio Sampler.vst3,
```

**Comment by arunas-cesonis** [comment]
I have only tested on Mac OS and very briefly on Windows so far. Getting same error in Carla " cannot allocate memory in static TLS block" as you are in Ardour.

**Comment by arunas-cesonis** [comment]
@crshrprt I fixed the issue with Ardour by disabling jemalloc. Reaper had same issue.
No able to load in Carla yet; it cannot find it when scanning
![Screenshot 2024-02-08 at 18 40 03](https://github.com/arunas-cesonis/live-sampler/assets/35488648/36e9fe5a-1b99-4b3f-87cf-f7463d6abeb4)

**Comment by crshrprt** [comment]
I can confirm that the latest commit fixed the problem. Now it runs in Bespoke Synth, Ardour and even in Carla.

![2024-02-08_20 49 15 575](https://github.com/arunas-cesonis/live-sampler/assets/114294020/ae62178f-e617-4fee-ba0c-6255663ce362)

Thank you. :)
